config/routes.rb
Pilot::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  mount Resque::Server.new, at: '/resque'

  # Landing page
  root :to => 'cms/pages#index'

  namespace :cms do
    resources :pages, only: [:show, :index]
  end
end

app/models/cms.rb
module Cms
  def self.table_name_prefix
    'cms_'
  end
end

app/models/cms/content.rb
class Cms::Content < ActiveRecord::Base
  include Cms
  has_one :cms_page, class_name: 'Cms::Page', foreign_key: :content_id
  has_many :items, class_name: 'Cms::Page::Item', dependent: :destroy, foreign_key: :parent_content_id
  attr_accessible :main_text
end

app/models/cms/footer.rb
class Cms::Footer < ActiveRecord::Base
  include Cms
  attr_accessible :text
end

app/models/cms/header.rb
class Cms::Header < ActiveRecord::Base
  include Cms
  attr_accessible :text, :image_path
end

app/models/cms/page.rb
# Abstract Page, STI model
class Cms::Page < ActiveRecord::Base
  include Cms
  belongs_to :header,  class_name: 'Cms::Header',  dependent: :destroy
  belongs_to :content, class_name: 'Cms::Content', dependent: :destroy
  belongs_to :footer,  class_name: 'Cms::Footer',  dependent: :destroy
  attr_accessible :name, :cms_url

  def has_parent?
    false
  end
end

app/models/cms/page/index.rb
# Index page
class Cms::Page::Index < Cms::Page
end

app/models/cms/page/item.rb
# An individual "item" listed by the index page
class Cms::Page::Item < Cms::Page
  belongs_to :parent_content, class_name: 'Cms::Content'

  # Instance methods

  def has_parent?
    parent_content.present?
  end

  def parent
    parent_content.try(:cms_page)
  end
end

app/models/cms/sync_job.rb
require 'open-uri'

class Cms::SyncJob
  SERVER = "http://localhost:5000"
  API = "/api/v1/"
  INDEX = 'index.json'

  @queue = :normal

  def self.perform
    self.new.perform
  end

  def perform
    if page = fetch_content(API + INDEX)["page"]
      index = build_or_update_index(page)
      index.save!
    end
  end

  private

  def build_or_update_index(data)
    index = Cms::Page::Index.first_or_initialize(cms_url: INDEX)
    build_cms_page(index, data)
    index
  end

  def build_cms_page(page, data)
    process_header(page,  data["header"])  if data["header"]
    process_content(page, data["content"]) if data["content"]
    process_footer(page,  data["footer"])  if data["footer"]
  end

  def process_header(page, header)
    attributes = { text: header["text"], image_path: header["image"] }
    page.header ? page.header.update_attributes(attributes) : page.build_header(attributes)
  end

  def process_content(page, content)
    games = content["games"]
    attributes = { main_text: content["main_text"] }
    page.content ? page.content.update_attributes(attributes) : page.build_content(attributes)

    games.try(:each) do |game|
      item = build_or_update_item(game)
      page.content.items << item
    end
  end

  def build_or_update_item(game)
    url = game["url"]

    item = if (existing = Cms::Page::Item.find_by_cms_url(url))
      existing.update_attributes(name: game["name"])
      existing
    else
      Cms::Page::Item.new(name: game["name"], cms_url: url)
    end

    if page = fetch_content(url)["page"]
      build_cms_page(item, page)
    end

    item
  end

  def process_footer(page, footer)
    attributes = { text: footer["text"] }
    page.footer ? page.footer.update_attributes(attributes) : page.build_footer(attributes)
  end

  def fetch_content(path)
    JSON.parse(open(SERVER + path).read)
  end
end

app/models/system_version.rb
class SystemVersion < ActiveRecord::Base
  attr_accessible :major, :minor
  def self.latest
    order(:created_at).last
  end

  def name
    "Pilot v#{version_name}"
  end

  def version_name
    "#{major}.#{minor}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cms/pages_controller.rb
class Cms::PagesController < ApplicationController
  def index
    @cms_page = Cms::Page.find_by_cms_url("index.json")
  end

  def show
    @cms_page = Cms::Page.find(params[:id])
  end
end

app/controllers/cms_pages_controller.rb
class CmsPagesController < ApplicationController
  def index
    @cms_page = Cms::Page.find_by_cms_url("index.json")
  end

  def show
    @cms_page = Cms::Page.find(params[:id])
  end
end

app/views/cms/pages/_page.html.haml
- if page
  .page
    .header
      %img{src: page.header.try(:image_path)}
      %h1= page.header.try(:text) or "Header missing"
      .content
        %h2= page.content.try(:main_text)
        %table.games
          %tbody
            - if page.content.try(:items)
              - for item in page.content.try(:items)
                %tr
                  %td
                    %a= link_to item.name, cms_page_path(item)
    .footer
      - if page.has_parent?
        %a= link_to "Back", cms_page_path(page.parent)
      %p= page.footer.try(:text)
- else
  %em
    No cms data appears to have been imported, please open
    %a{href: "http://localhost:3000/resque/schedule"}
      resque
    and queue a job

app/views/cms/pages/index.html.haml
= render partial: 'page', locals: { page: @cms_page }

app/views/cms/pages/show.html.haml
= render partial: 'page', locals: { page: @cms_page }

app/views/cms_page/_show.html.haml
.page
  .header
    %img{src: page.header.try(:image_path)}
    %h1= page.header.try(:text) or "Header missing"
    .content
      %h2= page.content.try(:main_text) or "Main text missing"
      %table.games
        %tbody
          - if page.content.try(:games)
            - for game in page.content.try(:games)
              = render partial: 'cms_page/game_row', locals: { game: game }

  .footer
    %p= page.footer.try(:text) or "Footer missing"

app/views/cms_pages/_page.html.haml
.page
  .header
    %img{src: page.header.try(:image_path)}
    %h1= page.header.try(:text) or "Header missing"
    .content
      %h2= page.content.try(:main_text) or "Main text missing"
      %table.games
        %tbody
          - if page.content.try(:items)
            - for item in page.content.try(:items)
              %tr
                %td
                  %a= link_to item.name, cms_page_path(item)
  .footer
    - if page.has_parent?
      %a= link_to "Back", cms_page_path(page.parent)
    %p= page.footer.try(:text) or "Footer missing"

app/views/layouts/_footer.html.haml
%footer
  System version: #{SystemVersion.latest.version_name}

app/views/layouts/_header.html.haml
%meta{charset: "utf-8"}/
%title= content_for?(:title) ? yield(:title) + " – Pilot" : "Pilot"
= stylesheet_link_tag "application", media: "all"
= javascript_include_tag "application"
= csrf_meta_tags

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_top_nav.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container
      = link_to SystemVersion.latest.name, root_path, class: 'navbar-brand'

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render partial: 'layouts/header'
  %body{class: "#{controller_name} #{action_name}"}
    = render partial: 'layouts/top_nav'
    .subnav.subnav-fixed
    .container
      .content
        .row
          .span12
            = render 'layouts/messages'
            = yield

      = render partial: 'layouts/footer'